### ISSUE TITLE
Setup leading to weird output

### ISSUE THREAD

**Issue by joshcho** [phronmophobic/llama.clj#10]
Idk if this is what I should be seeing, but I am getting some weird outputs. Maybe I need to use larger models?

![screenshot](https://github.com/phronmophobic/llama.clj/assets/6498524/fb51bcbf-a17c-4ceb-a90c-6a3917e608fb)

**Comment by phronmophobic** [comment]
I think the output is expected because you didn't follow the model's prompt format. If you follow the prompt format, it should not have weird output at the beginning.

llama2 7b prompt format: https://huggingface.co/TheBloke/llama2_7b_chat_uncensored-GGML#prompt-template-human-response

In general, the prompt formats makes the documentation a little awkward because each model has its own format. I think the newer gguf formats might make it easier to automatically follow the prompt format, but that hasn't been implemented yet.

Also, the ggml format has been deprecated and newer models are now generally using the gguf format.

Let me know if that fixes things for you.

**Comment by phronmophobic** [comment]
@joshcho I think using the correct prompt format will fix your issue and I haven't heard back. Feel free to reopen if you have anything to add.

**Comment by joshcho** [comment]
Yeah sorry for not replying back. It’s not an issue for me right now, will reopen if needed. Thanks.
