### ISSUE TITLE
Convenience Namespace for Using/Obtaining Models

### ISSUE THREAD

**Issue by jaketothepast** [phronmophobic/llama.clj#14]
Hello!

I saw this in the Roadmap, and I've somewhat implemented this myself for a side project using your library. Are you open to contributions with this item?

My approach:

I have a .edn file that defines the filepath to drop the models, in and if I load up my application and call into my namespace with a model URL that hasn't yet been downloaded, my code will download that model and return a promise and resolve the `llama-context` lazily in the application code. I can contribute this model loading namespace!

**Comment by phronmophobic** [comment]
I am open to contributions, but I am pretty opinionated. I've deprioritized the feature for making it easier to obtain and use models. One of the main ideas behind that feature was that each model has its own template format which is important for generating good responses. However, llama.cpp has since added support for including templates as part of the gguf format and those changes have already been implemented in llama.clj. With prompt template support, the feature seems mainly about downloading and caching models locally. That seems like a problem that might be better addressed using a more general third party library, but I could be convinced otherwise.

Some other prior art that influences how I think about the problem is the python huggingface library which offers a huggingface cli for downloading and caching models. Another reference is [DVC](https://dvc.org/).

It sounds like what you built might be interesting and useful to others. Another alternative might be to have it has a separate library which I could link to in the docs.

I've rambled a bit, but it's hard to give more specific feedback without a more detailed proposal. Do you have a link to what the code might look like?

**Comment by jaketothepast** [comment]
I agree with you. I believe having a separate library to load and cache models would follow the Clojure ethos of keeping everything functional and small. I will split out what I've been working on into a separate model loading library for use with `llama.clj`, to keep things focused.

Here's the idea boiled down:

```clojure
(defn- download-model
  "Either download the model, or return the path."
  [url local-dir]
  (let [filename (model-name url)
        model-file (io/file local-dir filename)
        file-write-promise (promise)]
    (if (.exists model-file)
      (deliver file-write-promise (.getCanonicalPath model-file)) ;; It exists, deliver the path
      (future (do ;; It doesn't exist, download it on the background thread.
                (when (not (.exists model-file))
                  (with-open [in (io/input-stream (io/as-url url))
                              out (io/output-stream model-file)]
                    (io/copy in out)))
                (deliver file-write-promise (.getCanonicalPath model-file)))))
    file-write-promise))
```

When my application loads, it will run this code and return the promise that we have downloaded the file. I don't deref the promise until the application tries to run a completion using `llama/generate`. it will then call deref the promise and call `llama/create-context` and subsequent calls use the context that I've swapped into an atom in that namespace.

```clojure
(defn- retrieve-model
  "Get the model weights, optionally download the model weights from the internet
  first. If we download the model weights from the internet, then write the weight
  location to the cache."
  [url local-dir]
  (let [dir (io/file local-dir)]
    ;; Handle creating our model dir and our cache file location
    (or (.exists dir) (.mkdirs dir)) ; Create the local directory, this didn't expand tilde
    (let [model-location (download-model url local-dir)] ;; Gets a promise
      (swap! local-llm-state assoc :model-location model-location))))
```

If this code seems useful, I can adapt it for your library, but otherwise I can split this into my own third party library for model caching/usage as well!

**Comment by phronmophobic** [comment]
Sounds good. I think a separate library might be the best place for now.

Just some thoughts on the `download-model` function:

- If two different threads call `download-model`, it creates a race condition where the file may be downloaded multiple times.
- If an error occurs while downloading the model, then you may end up with a corrupt model file. One common option is to download to a temporary file and then move it to the desired location on successful completion and optional integrity check. File moves tend to be atomic on most operating systems.

**Comment by jaketothepast** [comment]
Thank you for your thoughts! Really helpful for getting started
